const API_PREFIX = "/api";
let state = { authenticated: false, configured: false, session: null, modules: [], providers: [], filter: "all", query: "", logs: false };
const app = document.getElementById("app");

function parse(value) { return typeof value === "string" ? JSON.parse(value) : value; }
function esc(value) { return String(value ?? "").replace(/[&<>"']/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c])); }
async function get(name) { const response = await fetch(`${API_PREFIX}/${name}`, { credentials: "same-origin" }); const data = parse(await response.json()); if (!response.ok || data?.success === false) throw new Error(data.error || "请求失败"); return data; }
async function post(name, payload) { const response = await fetch(`${API_PREFIX}/${name}`, { method: "POST", credentials: "same-origin", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload || {}) }); const data = parse(await response.json()); if (!response.ok || data?.success === false) throw new Error(data.error || "请求失败"); return data; }
function showToast(message) { const node = document.createElement("div"); node.className = "toast"; node.textContent = message; document.body.appendChild(node); setTimeout(() => node.remove(), 2200); }
function loginView(message = "") { app.innerHTML = `<section class="login"><div class="login-side"><div class="brand"><span class="brand-mark">核</span><div><strong>凝心溯溪</strong><small>模块运营中心</small></div></div><div class="login-copy"><h1>把每个模块，放进同一张工作台。</h1><p>管理员账户由“核” Page 创建和维护。WebUI 只负责安全登录，不提供注册入口。</p></div><small>Dashboard Page 二次认证 · 管理员会话受服务端控制</small></div><div class="login-main"><form class="login-card" id="login-form"><h2>登录模块运营中心</h2><p>${state.configured ? "请输入在“核” Page 中配置的管理员账户。" : "当前还没有可用管理员，请先回到“核” Page 设置管理员。"}</p><div class="field"><label for="username">管理员账户</label><input id="username" name="username" autocomplete="username" required ${state.configured ? "" : "disabled"}></div><div class="field"><label for="password">密码</label><input id="password" name="password" type="password" autocomplete="current-password" required ${state.configured ? "" : "disabled"}></div><div class="error" role="alert">${esc(message)}</div><button class="btn primary" type="submit" ${state.configured ? "" : "disabled"}>安全登录</button><div class="note">WebUI 不在浏览器保存账户、密码或会话令牌。请在“核” Page 管理多个管理员、角色和禁用状态。</div></form></div></section>`; const form = document.getElementById("login-form"); form?.addEventListener("submit", async event => { event.preventDefault(); const data = new FormData(form); try { const result = await post("login", { username: data.get("username"), password: data.get("password") }); state.authenticated = true; state.session = result.session; await loadDashboard(); } catch (error) { loginView(error.message); } }); }
function filtered() { return state.modules.filter(item => (state.filter === "all" || (state.filter === "normal" && item.status === "normal") || (state.filter === "offline" && item.status !== "normal")) && (!state.query || `${item.display_name} ${item.plugin_id}`.toLowerCase().includes(state.query.toLowerCase()))); }
function moduleRows() { const list = filtered(); return list.length ? list.map(item => `<tr><td><div class="module"><span class="mark" style="--color:${color(item.plugin_id)}">${esc(item.display_name.slice(-1))}</span><div><b>${esc(item.display_name)}</b><small>${esc(item.plugin_id)}</small></div></div></td><td><span class="status ${item.status === "normal" ? "" : "off"}">${item.status === "normal" ? "正常" : "已停用/未加载"}</span></td><td><span class="pill">${item.contracts} 条契约</span></td><td><code>v${esc(item.version || "未知")}</code></td><td>${item.update_available ? "有更新" : "当前"}</td><td><button class="link" data-diagnostic="${esc(item.plugin_id)}">诊断</button></td></tr>`).join("") : `<tr><td colspan="6" style="padding:40px;text-align:center;color:#667085">没有匹配的可信模块。</td></tr>`; }
function color(id) { const colors = ["#3b82b9", "#7653a6", "#cb4d48", "#db7d27", "#2c927c", "#3975aa", "#414a55", "#be385c"]; let sum = 0; for (const char of id) sum += char.charCodeAt(0); return colors[sum % colors.length]; }
function dashboard() { const normal = state.modules.filter(x => x.status === "normal").length; const offline = state.modules.length - normal; app.innerHTML = `<div class="shell">${rail()}<main class="main"><header class="topbar"><div class="crumb">凝心溯溪 / <b>核 · 模块运营中心</b></div><div class="top-actions"><button class="btn" id="refresh">刷新</button><button class="btn" id="logout">退出登录</button></div></header><div class="content"><div class="page-head"><div><div class="eyebrow">系列治理 / 生产状态</div><h1>模块运营中心</h1><p>统一查看可信自有模块的运行状态、版本、契约与诊断入口。</p></div><div class="actions"><button class="btn" id="export">导出摘要</button><button class="btn primary" id="check">运行全量检查</button></div></div><div class="stats"><div class="stat"><label>可信模块</label><strong>${state.modules.length}</strong><small>来自可信登记</small></div><div class="stat"><label>运行正常</label><strong>${normal}</strong><small>核心链路可用</small></div><div class="stat"><label>需关注</label><strong>${offline}</strong><small>非阻断状态</small></div><div class="stat"><label>契约发现</label><strong>已接入</strong><small>版本化能力</small></div><div class="stat"><label>管理边界</label><strong>安全</strong><small>高危操作仍需确认</small></div></div><section class="workspace"><div class="workspace-head"><div class="section-title"><h2>系列模块</h2><span>${filtered().length} 个匹配当前视图</span></div><div class="filters"><label class="search">⌕<input id="query" placeholder="搜索模块名称或 ID" value="${esc(state.query)}"></label><div class="seg"><button data-filter="all" class="${state.filter === "all" ? "active" : ""}">全部</button><button data-filter="normal" class="${state.filter === "normal" ? "active" : ""}">正常</button><button data-filter="offline" class="${state.filter === "offline" ? "active" : ""}">需关注</button></div><span class="grow"></span><button class="btn" id="reload">刷新状态</button></div></div><div class="table-wrap"><table class="table"><thead><tr><th>模块</th><th>运行状态</th><th>契约</th><th>版本</th><th>更新</th><th>操作</th></tr></thead><tbody>${moduleRows()}</tbody></table></div><div class="footer"><span>未来模块会在通过可信登记和仓库归属校验后自动出现。</span><span>${state.modules.length} 个模块</span></div></section></div></main><nav class="mobile-nav"><button id="mobile-modules"><span>▦</span>模块</button><button id="mobile-logs"><span>≡</span>日志</button><button id="mobile-refresh"><span>↻</span>刷新</button><button id="mobile-logout"><span>⇥</span>退出</button></nav></div>${state.logs ? `<section class="log open"><div class="log-head"><b>系列活动日志</b><button class="btn" id="close-logs">收起</button></div><div class="log-body">${esc(state.providers.map(item => `${item.display_name} · ${item.status}`).join("\\n") || "暂无新的诊断摘要")}</div></section>` : ""}`; bindDashboard(); }
function rail() { return `<aside class="rail"><div class="brand"><span class="brand-mark">核</span><div><strong>凝心溯溪</strong><small>模块运营中心</small></div></div><div class="nav-label">工作区</div><nav class="nav"><button class="active">▦　模块总览</button><button>⌁　运行诊断</button><button id="nav-logs">≡　活动日志</button><button>↻　更新与回滚</button><button>⚙　全局设置</button><button>◇　安全与账户</button></nav><div class="spacer"></div><div class="health"><b>系列健康度</b><p>${state.modules.length} 个可信模块已纳管。模块发现不执行任意第三方代码。</p><div class="bar"><i></i></div></div><div class="user"><span class="avatar">管</span><span>${esc(state.session?.username || "管理员")}</span><button class="logout" id="rail-logout">↪</button></div></aside>`; }
function bindDashboard() { document.getElementById("logout")?.addEventListener("click", logout); document.getElementById("rail-logout")?.addEventListener("click", logout); document.getElementById("mobile-logout")?.addEventListener("click", logout); document.getElementById("refresh")?.addEventListener("click", loadDashboard); document.getElementById("reload")?.addEventListener("click", loadDashboard); document.getElementById("check")?.addEventListener("click", async () => { await loadDashboard(); showToast("已完成可信模块状态检查"); }); document.getElementById("export")?.addEventListener("click", exportSummary); document.getElementById("nav-logs")?.addEventListener("click", () => { state.logs = true; dashboard(); }); document.getElementById("mobile-logs")?.addEventListener("click", () => { state.logs = true; dashboard(); }); document.getElementById("close-logs")?.addEventListener("click", () => { state.logs = false; dashboard(); }); document.getElementById("mobile-refresh")?.addEventListener("click", loadDashboard); document.querySelectorAll("[data-diagnostic]").forEach(node => node.addEventListener("click", () => loadDiagnostics(node.dataset.diagnostic))); document.querySelectorAll("[data-filter]").forEach(node => node.addEventListener("click", () => { state.filter = node.dataset.filter; dashboard(); })); const query = document.getElementById("query"); query?.addEventListener("input", () => { state.query = query.value; dashboard(); requestAnimationFrame(() => { const next = document.getElementById("query"); next?.focus(); next?.setSelectionRange(state.query.length, state.query.length); }); }); }
async function loadDiagnostics(pluginId = "") { try { const result = await post("diagnostics", pluginId ? { plugin_ids: [pluginId] } : {}); state.providers = result.providers || []; state.logs = true; dashboard(); } catch (error) { showToast(error.message, true); } }
function exportSummary() { const payload = { generated_at: new Date().toISOString(), modules: state.modules.map(item => ({ plugin_id: item.plugin_id, version: item.version, status: item.status, contracts: item.contracts })) }; const url = URL.createObjectURL(new Blob([JSON.stringify(payload, null, 2)], { type: "application/json" })); const link = document.createElement("a"); link.href = url; link.download = "series-control-summary.json"; link.click(); URL.revokeObjectURL(url); showToast("已生成脱敏诊断摘要"); }
async function loadDashboard() { try { const session = await get("session"); state.configured = !!session.configured; if (!session.authenticated) { state.authenticated = false; loginView(); return; } state.authenticated = true; state.session = session.session; const modules = await get("modules"); state.modules = modules.modules || []; dashboard(); } catch (error) { loginView(error.message); } }
async function logout() { try { await post("logout", {}); } finally { state.authenticated = false; state.session = null; loginView(); } }
async function start() { try { await loadDashboard(); } catch (error) { loginView(error.message); } }
start();
